In [1]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)

In [5]:
#create an object called iris with iris data
iris=load_iris()
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
  #add new column for the species name
df['species']=pd.Categorical.from_codes(iris.target, iris.target_names)
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [7]:
#create test and train data
df['is_tarin']=np.random.uniform(0,1,len(df)) <= .75
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,is_tarin
0,5.1,3.5,1.4,0.2,setosa,True
1,4.9,3.0,1.4,0.2,setosa,True
2,4.7,3.2,1.3,0.2,setosa,True
3,4.6,3.1,1.5,0.2,setosa,True
4,5.0,3.6,1.4,0.2,setosa,True

In [8]:
#create dataframes with test rows and training rows
train,test=df[df['is_tarin']==True], df[df['is_tarin']==False]
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:', len(test))

Number of observations in the training data: 118
Number of observations in the test data: 32

In [11]:
#create a list of features columns names
features=df.columns[:4]
print(features)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [12]:
#convert each species name into digits
y=pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
#creating random forest classifier
clf=RandomForestClassifier(n_jobs=2, random_state=0,)
#training classifier
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [18]:
#apply the trained classifier to test
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
test[features]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
10                 5.4               3.7                1.5               0.2
13                 4.3               3.0                1.1               0.1
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
23                 5.1               3.3                1.7               0.5
27                 5.2               3.5                1.5               0.2
31                 5.4               3.4                1.5               0.4
38                 4.4               3.0                1.3               0.2
52                 6.9               3.1                4.9               1.5
66                 5.6               3.0                4.5               1.5
68                 6.2               2.2                4.5               1.5
70                 5.9               3.2                4.8               1.8
72                 6.3               2.5                4.9               1.5
89                 5.5               2.5                4.0               1.3
98                 5.1               2.5                3.0               1.1
103                6.3               2.9                5.6               1.8
109                7.2               3.6                6.1               2.5
111                6.4               2.7                5.3               1.9
114                5.8               2.8                5.1               2.4
116                6.5               3.0                5.5               1.8
118                7.7               2.6                6.9               2.3
122                7.7               2.8                6.7               2.0
140                6.7               3.1                5.6               2.4
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
147                6.5               3.0                5.2               2.0
149                5.9               3.0                5.1               1.8

In [22]:
#view predicted probabilities of the first 10 observation
clf.predict_proba(test[features][10:20])

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.67, 0.33],
       [0.  , 1.  , 0.  ],
       [0.  , 0.82, 0.18],
       [0.  , 0.03, 0.97],
       [0.  , 0.42, 0.58],
       [0.  , 0.99, 0.01],
       [0.  , 0.96, 0.04]])

In [23]:
#mapping names for the plants
preds=iris.target_names[clf.predict(test[features])]
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [24]:
#view actual species
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [25]:
#confusion matris
pd.crosstab(test['species'], preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12